package com.Aparna.employeeapp.feignClient;

import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;

import com.Aparna.employeeapp.response.AddressResponse;
//http://localhost:8081/Address_Service/api/address/110
@FeignClient(name="AddressService",url="http://localhost:8081",path = "/Address_Service/api/")
//@ribbonClient(name="AddressService")dis=u can add n number of  servers manuvally(8081,8082 in db lo)
public interface AddressClient {   //proxy means implementation generated by spring in hiting the method
	  //@requestline("get")                                
	@GetMapping("/address/{id}")
	AddressResponse getAddressByEmployeeId(@PathVariable("id") Long id);

}
